apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: influxdb
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.9.3
    helm:
      releaseName: influxdb
      values: |
        config:
          clients:
            - url: http://loki-gateway.logging/loki/api/v1/push
              tenant_id: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true