apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memcached
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: memcached
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 6.7.1
    helm:
      releaseName: memcached
      values: |
        architecture: high-availability
        autoscaling: 
          enabled: true
          replicaCount: 2
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true