apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-operator
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: mysql-operator
    repoURL: https://mysql.github.io/mysql-operator/
    targetRevision: 2.1.1
    helm:
      releaseName: mysql-operator
      values:
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true