apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-operator
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: redis-operator
    repoURL: https://spotahome.github.io/redis-operator
    targetRevision: 3.3.0
    helm:
      releaseName: redis-operator
      values:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: redis-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true