apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-operator
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: redis-operator
    repoURL: https://ot-container-kit.github.io/helm-charts
    targetRevision: 0.15.9
    helm:
      releaseName: redis-operator
      values:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: redis-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-sentinel
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: redis-sentinel
    repoURL: https://ot-container-kit.github.io/helm-charts
    targetRevision: 0.15.9
    helm:
      releaseName: redis-sentinel
      values: |
        redissentinel:
          clusterSize: 3
        redisSentinelConfig:
          redisReplicationName: "redis-replication"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: redis-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true