apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sentry
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: sentry
    repoURL: https://sentry-kubernetes.github.io/charts
    targetRevision: 20.12.1
    helm:
      releaseName: sentry
      values: |
        sentry:
          worker:
            replicas: 1
        kafka:
          replicaCount: 1
        clickhouse:
          clickhouse:
            replicas: 1
        redis:
          replica:
            replicaCount: 1
        zookeeper:
          replicaCount: 1
        rabbitmq:
          replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: sentry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true