apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: redis-sentinel
    repoURL: https://ot-container-kit.github.io/helm-charts
    targetRevision: 0.15.12
    helm:
      releaseName: redis-sentinel
      values: |
        redisSentinel:
          clusterSize: 3
        redisSentinelConfig:
          redisReplicationName: "redis-replication"
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true