apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: grafana
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
  ports:
  - port: 80
    nodePort: 31000
    targetPort: 3000
    protocol: TCP