---
apiVersion: v1
kind: Secret
metadata:
  name: mypwds
type: Opaque
data:
  rootUser: cm9vdA==      # base64 encoded "root"
  rootHost: JSA=          # base64 encoded "%"
  rootPassword: cm9vdA==  # base64 encoded "root"
---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mycluster
spec:
  secretName: mypwds
  tlsUseSelfSigned: true
  instances: 2
  router:
    instances: 1