apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30222
    protocol: TCP
  selector:
    component: mysqlrouter
    mysql.oracle.com/cluster: mycluster
    tier: mysql
---
apiVersion: v1
kind: Secret
metadata:
  name: mypwds
type: Opaque
data:
  rootUser: cm9vdA==      # base64 encoded "root"
  rootHost: JSA=          # base64 encoded "%"
  rootPassword: cm9vdA==  # base64 encoded "root"
---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mycluster
spec:
  secretName: mypwds
  tlsUseSelfSigned: false
  instances: 2
  version: 8.0.0
  router:
    instances: 1
    version: 8.0.0
  datadirVolumeClaimTemplate:
    accessModes: 
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  initDB:
    clone:
      donorUrl: mycluster-0.private-isu:3306
      rootUser: root
      secretKeyRef:
        name: mypwds
  mycnf: |
    [mysqld]
    default_authentication_plugin=mysql_native_password