---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb
resources:
  - github.com/metallb/metallb/config/native?ref=v0.13.12
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: config
  namespace: metallb
spec:
  addresses:
  -  192.168.11.128-192.168.11.199
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: config
  namespace: metallb
spec:
  ipAddressPools:
  - config
EOF