- name: apt
  apt:
    name:
    - haproxy
    - keepalived

- name: copy
  copy:
    src: ./files/haproxy_wk/haproxy/argocd.cfg
    dest: /etc/haproxy/
    mode: '0644'
  ignore_errors: yes

- name: copy
  copy:
    src: ./files/haproxy_wk/haproxy/haproxy.cfg
    dest: /etc/haproxy/
    mode: '0644'
  ignore_errors: yes

- name: replace
  replace:
    path: /etc/haproxy/argocd.cfg
    regexp: '\$\{ARGOCD_VIP\}'
    replace: "{{ ARGOCD_VIP }}"
  ignore_errors: yes

- name: replace
  replace:
    path: /etc/haproxy/argocd.cfg
    regexp: '\$\{WK_IPS\[0\]\}'
    replace: "{{ WK_IPS_1 }}"
  ignore_errors: yes

- name: replace
  replace:
    path: /etc/haproxy/argocd.cfg
    regexp: '\$\{WK_IPS\[1\]\}'
    replace: "{{ WK_IPS_2 }}"
  ignore_errors: yes

- name: replace
  replace:
    path: /etc/haproxy/argocd.cfg
    regexp: '\$\{WK_IPS\[2\]\}'
    replace: "{{ WK_IPS_3 }}"
  ignore_errors: yes

- name: shell
  shell: echo "net.ipv4.ip_nonlocal_bind = 1" >> /etc/sysctl.conf

- name: shell
  shell: sysctl -p

- name: copy
  copy:
    src: ./files/haproxy_wk/keepalived/argocd.conf
    dest: /etc/keepalived/
    mode: '0644'
  ignore_errors: yes

- name: copy
  copy:
    src: ./files/haproxy_wk/keepalived/keepalived.conf
    dest: /etc/keepalived/
    mode: '0644'
  ignore_errors: yes

- name: replace
  replace:
    path: /etc/keepalived/argocd.conf
    regexp: '\$\{ARGOCD_VIP\}'
    replace: "{{ ARGOCD_VIP }}"
  ignore_errors: yes

- name: replace
  replace:
    path: /etc/keepalived/argocd.conf
    regexp: '\$\{WK_IPS\[0\]\}'
    replace: "{{ WK_IPS_1 }}"
  ignore_errors: yes

- name: replace
  replace:
    path: /etc/keepalived/argocd.conf
    regexp: '\$\{WK_IPS\[1\]\}'
    replace: "{{ WK_IPS_2 }}"
  ignore_errors: yes

- name: replace
  replace:
    path: /etc/keepalived/argocd.conf
    regexp: '\$\{WK_IPS\[2\]\}'
    replace: "{{ WK_IPS_3 }}"
  ignore_errors: yes

- name: systemd
  systemd:
    name: keepalived
    state: restarted
    enabled: true
  ignore_errors: yes

- name: systemd
  systemd:
    name: haproxy
    state: restarted
    enabled: true
  ignore_errors: yes