apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
  namespace: myapp
  labels:
    app: redis
    app.kubernetes.io/name: redis
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
