apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: myapp
spec:
  selector:
    matchLabels:
      app: redis
      app.kubernetes.io/name: redis
  containers:
  - name: redis
    image: kubernetes/redis:v1
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: 200m
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    - mountPath: /redis-master
      name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: redis