apiVersion: v1
kind: Service
metadata:
  labels:
    service: k8s-sentry
  name: k8s-sentry
  namespace: k8s-sentry
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30050
      protocol: TCP
  selector:
    service: k8s-sentry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-sentry
spec:
  selector:
    matchLabels:
      app: sentry-kubernetes
  template:
    metadata:
      labels:
        app: sentry-kubernetes
    spec:
      serviceAccountName: k8s-sentry
      containers:
        - name: sentry-kubernetes
          image: wichert/k8s-sentry:1.4.1
          env:
            - name: SENTRY_DSN
              value: "insert-your-DSN-here"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              memory: 10Mi
              cpu: 5m
            limits:
              memory: 64Mi
              cpu: 50m