apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: promtail
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.15.3
    helm:
      releaseName: promtail
      values: |
        config:
          clients:
            - url: http://loki-gateway.logging/loki/api/v1/push
              tenant_id: 1
          snippets:
            extraScrapeConfigs: |
              - job_name: syslog
                syslog:
                  listen_address: 0.0.0.0:{{ .Values.extraPorts.syslog.containerPort }}
                  labels:
                    job: syslog
                relabel_configs:
                  - source_labels:
                      - __syslog_message_hostname
                    target_label: hostname
                  - source_labels:
                      - __syslog_message_app_name
                    target_label: app
                  - source_labels:
                      - __syslog_message_severity
                    target_label: level
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true