# ref: https://qiita.com/arila/items/3c453b7e802639eebdea

apiVersion: v1
kind: ConfigMap
metadata:
  name: misskey-config
data:
  default.yml: |
    url: https://example.tld/
    port: 3000
    db:
      host: postgres-cluster.misskey
      port: 5432
      db: misskey
      user: misskey-user
      pass: misskey-pass
    redis:
      host: redis.misskey
      port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: misskey-deployment
spec:
  selector:
    matchLabels:
      app: misskey
  replicas: 2
  template:
    metadata:
      labels:
        app: misskey
    spec:
      containers:
      - name: misskey
        image: misskey/misskey:latest # 2023.11.1
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: misskey-files
          mountPath: /misskey/files
        - name: misskey-config
          mountPath: /misskey/.config
        command: ["pnpm", "run", "migrateandstart"]
      volumes:
      - name: misskey-files
        configMap:
          name: misskey-files
      - name: misskey-config
        configMap:
          name: misskey-config
  volumeClaimTemplates:
  - metadata:
      name: misskey-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: misskey-service
  labels:
    app: misskey
spec:
  type: clusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: misskey