# ref: https://qiita.com/arila/items/3c453b7e802639eebdea

apiVersion: v1
kind: ConfigMap
metadata:
  name: misskey-config
data:
  default.yml: |
    url: https://example.tld/
    port: 3000
    db:
      host: postgres-cluster.misskey
      port: 5432
      db: misskey
      user: misskey-user
      pass: misskey-pass
    redis:
      host: redis-service.misskey
      port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: misskey-deployment
spec:
  selector:
    matchLabels:
      app: misskey
  replicas: 2
  template:
    metadata:
      labels:
        app: misskey
    spec:
      containers:
      - name: misskey
        image: ghcr.io/niri-la/misskey.niri.la:v13.13.2-kinel
        imagePullPolicy: IfNotPresent
        env:
        - name: PGSSLMODE
          value: require
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /misskey/.config
          name: misskey-config
        # command: ["pnpm", "run", "migrateandstart"]
      volumes:
      - name: misskey-config
        configMap:
          name: misskey-config
          items:
          - key: default.yml
            path: default.yml
---
apiVersion: v1
kind: Service
metadata:
  name: misskey-service
  labels:
    app: misskey
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: misskey