# ref: https://qiita.com/arila/items/3c453b7e802639eebdea

apiVersion: v1
kind: ConfigMap
metadata:
  name: misskey-config
data:
  default.yml: |
    url: https://example.tld/
    port: 3000
    db:
      host: postgres-cluster.misskey
      port: 5432
      db: misskey
      user: misskey-user
      pass: misskey-pass
    redis:
      host: redis-service.misskey
      port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: misskey-deployment
spec:
  selector:
    matchLabels:
      app: misskey
  replicas: 1
  template:
    metadata:
      labels:
        app: misskey
    spec:
      containers:
        - name: misskey
          image: misskey/misskey:2023.10.2
          env:
          - name: PGSSLMODE
            value: require
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: "0"
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: misskey-config
              mountPath: /misskey/.config
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2048Mi
          readinessProbe:
            httpGet:
              path: /
              port: 3000
      volumes:
        - name: misskey-config
          configMap:
            name: misskey-config
            items:
              - key: default.yml
                path: default.yml
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 20
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - misskey
                topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: misskey-service
  labels:
    app: misskey
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: misskey