apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-master-config
data:
  redis.conf: |
    port 6379
    bind 0.0.0.0 ::1
    requirepass password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-redis-master
  labels:
    name: deployment-redis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-master
  template:
    metadata:
      labels:
        name: redis-master
    spec:
      subdomain: master
      containers:
        - name: redis
          image: redis:6
          command:
            - "redis-server"
          args:
            - "--protected-mode"
            - "yes"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: master-config
              mountPath: "/etc/redis"
              readOnly: true
      volumes:
        - name: master-config
          configMap:
            name: redis-master-config
---
apiVersion: v1
kind: Service
metadata:
  name: service-redis-master
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis-master