apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-redis-replica
  labels:
    name: deployment-redis-replica
spec:
  replicas: 2
  selector:
    matchLabels:
      name: redis-replica
  template:
    metadata:
      labels:
        name: redis-replica
    spec:
      subdomain: replica
      containers:
        - name: redis
          image: redis:6
          command:
            - "redis-server"
          args:
            - "--slaveof"
            - "service-redis-master.default.svc.cluster.local"
            - "6379"
            - "--protected-mode"
            - "no"
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: service-redis-replica
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: redis-replica