apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres-cluster
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    zalando:  # database owner
    - superuser
    - createdb
    misskey-user:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    foo: zalando  # dbname: owner
    misskey: misskey-user  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "15"

# ref: https://github.com/zalando/postgres-operator/tree/v1.10.1

# export PGPASSWORD=$(kubectl get secret -n misskey postgres.postgres-cluster.credentials.postgresql.acid.zalan.do -o 'jsonpath={.data.password}' | base64 -d)
# export PGSSLMODE=require
# psql -U postgres -h 10.0.2.146
