apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30052
    protocol: TCP
  selector:
    app: postgres-zalando
    kind: postgres-cluster
---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres-cluster
  labels:
    app: postgres-zalando
    kind: postgres-cluster
spec:
  env:
    - name: POSTGRES_DB
      value: misskey
    - name: POSTGRES_USER
      value: misskey-user
    - name: POSTGRES_PASSWORD
      value: misskey-pass
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    zalando:  # database owner
      - superuser
      - createdb
    misskey-user:  # database owner
      - superuser
      - createdb
    foo_user: []  # role for application foo
  databases:
    foo: zalando  # dbname: owner
    misskey: misskey-user  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "15"
  #   parameters:
  #     shared_buffers: "64MB"
  #     max_connections: "50"
  #     log_statement: "all"
  # patroni:
  #   initdb:
  #     encoding: "UTF8"
  #     locale: "ja_JP.UTF-8"
  #     data-checksums: "true"
  #   pg_hba:
  #   - hostssl all all 0.0.0.0/0 md5
  #   - host all all 0.0.0.0/0 md5

# ref: https://github.com/zalando/postgres-operator/tree/v1.10.1

# k delete pod -n misskey postgres-cluster-0
# k delete pod -n misskey postgres-cluster-1
# k delete pvc -n misskey pgdata-postgres-cluster-0
# k delete pvc -n misskey pgdata-postgres-cluster-1

# export PGPASSWORD=$(kubectl get secret -n misskey postgres.postgres-cluster.credentials.postgresql.acid.zalan.do -o 'jsonpath={.data.password}' | base64 -d)
# export PGSSLMODE=require
# kd pod -n misskey postgres-cluster-0 | grep IP
# psql -U postgres -h 10.0.2.11

# ALTER ROLE "misskey-user" WITH PASSWORD 'misskey-pass';
# export PGPASSWORD=misskey-pass
# export PGSSLMODE=require
# psql -U misskey-user -d misskey -h 10.0.2.11

# export PGPASSWORD=$(kubectl get secret -n misskey misskey-user.postgres-cluster.credentials.postgresql.acid.zalan.do -o 'jsonpath={.data.password}' | base64 -d)
# export PGSSLMODE=require
# kd pod -n misskey postgres-cluster-0 | grep IP
# psql -U misskey-user -d misskey -h 10.0.2.11