apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30989
    protocol: TCP
  selector:
    app.kubernetes.io/instance: 
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: misskey-apps
  namespace: argocd
spec:
  project: misskey
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.6.1
    helm:
      releaseName: redis
      values: |
        image:
          repository: bitnami/redis
        auth:
          sentinel: true
        master:
          count: 1
          containerPorts:
            redis: 6379
          persistence:
            enabled: true
            storageClass: nfs-share
            accessModes:
              - ReadWriteOnce
            size: 8Gi
          persistentVolumeClaimRetentionPolicy:
            enabled: false
            whenScaled: Retain
            whenDeleted: Retain
        replica:
          replicaCount: 3
          externalMaster:
            enabled: false
          containerPorts:
            redis: 6379
          persistence:
            enabled: true
            path: /data
            storageClass: nfs-share
            accessModes:
              - ReadWriteOnce
            size: 8Gi
          persistentVolumeClaimRetentionPolicy:
            enabled: false
            whenScaled: Retain
            whenDeleted: Retain
        sentinel:
          enabled: true
          masterSet: mymaster
          quorum: 2
          getMasterTimeout: 90
          automateClusterRecovery: false
          redisShutdownWaitFailover: true
          downAfterMilliseconds: 60000
          failoverTimeout: 180000
          containerPorts:
            sentinel: 26379
          persistence:
            enabled: true
            path: /data
            storageClass: nfs-share
            accessModes:
              - ReadWriteOnce
            size: 8Gi
          persistentVolumeClaimRetentionPolicy:
            enabled: false
            whenScaled: Retain
            whenDeleted: Retain
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true