apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-slave-config
data:
  redis.conf: |
    port 6379
    bind 0.0.0.0 ::1
    masterauth password
    replicaof redis-master-service.misskey 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-slave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: slave
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: slave-config
              mountPath: "/etc/redis"
              readOnly: true
      volumes:
        - name: slave-config
          configMap:
            name: redis-slave-config
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-health-check
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-health-check
  template:
    metadata:
      labels:
        app: redis-health-check
    spec:
      containers:
      - name: health-check-container
        image: YOUR_CUSTOM_IMAGE
        command: ["sh", "-c", "while true; do redis-cli -h redis-master-service.misskey -p 6379 INFO replication | grep role:master; if [ $? -eq 0 ]; then exit 0; else sleep 5; fi; done"]