- name: shell
  shell: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

- name: shell
  shell: helm repo add cilium https://helm.cilium.io/

- name: copy
  copy:
    src: ./files/cp/values.yaml
    dest: ~/
    owner: root
    group: root
    mode: '0644'
  ignore_errors: yes

- name: Execute helm
  shell: |
    helm install cilium cilium/cilium \
        --version 1.15.0-pre.2 \
        --namespace kube-system \
        -f ~/values.yaml
  register: result
  changed_when: false
- name: Show stdout helm
  debug:
    msg: "{{ result.stdout_lines }}"

- name: copy
  copy:
    src: ./files/cp/kustomization.yaml
    dest: ~/
    owner: root
    group: root
    mode: '0644'
  ignore_errors: yes

- name: shell
  shell: kubectl create namespace metallb

- name: shell
  shell: kubectl apply -k ~/
