- name: Copy ha-backup.sh
  copy:
    src: "./files/k8s/ha-backup.sh"
    dest: ~/work/
    mode: '0755'

- name: Copy join_kubeadm_cp.yaml
  copy:
    src: "{{ item }}"
    dest: ~/
    mode: '0755'
  with_fileglob:
  - "/root/work/ansible/files/k8s/fetch/join_kubeadm_cp.yaml"

- name: Execute ha-backup.sh
  shell: bash ~/work/ha-backup.sh

- name: Execute join
  shell: kubeadm join --config ~/join_kubeadm_cp.yaml
  register: result
  changed_when: false
- name: Show stdout join
  debug:
    msg: "{{ result.stdout_lines }}"