- name: Copy ha-master.sh
  copy:
    src: "./files/k8s/ha-master.sh"
    dest: ~/work/
    mode: '0755'

- name: Copy common.sh
  copy:
    src: "./files/k8s/common.sh"
    dest: ~/work/
    mode: '0755'

- name: Copy setup.sh
  copy:
    src: "./files/k8s/setup.sh"
    dest: ~/work/
    mode: '0755'