kubeProxyReplacement: strict
k8sServiceHost: 192.168.11.100 # modify it if necessary
k8sServicePort: 8443
loadBalancer:
  algorithm: maglev
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
  metrics:
    enabled:
    - dns:query;ignoreAAAA
    - drop
    - tcp
    - flow
    - icmp
    - http
    - port-distribution