apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 
resources:
  - https://raw.githubusercontent.com/mysql/mysql-operator/trunk/deploy/deploy-crds.yaml
  - https://raw.githubusercontent.com/mysql/mysql-operator/trunk/deploy/deploy-operator.yaml