# Exe Command
#
# helm template redis bitnami/redis --version 18.6.1 --kube-version 1.28.3 -f values.yaml > manifest.yaml
#
# ref: https://artifacthub.io/packages/helm/bitnami/redis

auth:
  enabled: false
  sentinel: false
master:
  count: 1
  containerPorts:
    redis: 6379
  persistence:
    enabled: true
    storageClass: nfs-share
    accessModes:
      - ReadWriteOnce
    size: 8Gi
  persistentVolumeClaimRetentionPolicy:
    enabled: false
    whenScaled: Retain
    whenDeleted: Retain
replica:
  replicaCount: 3
  externalMaster:
    enabled: false
  containerPorts:
    redis: 6379
  persistence:
    enabled: true
    path: /data
    storageClass: nfs-share
    accessModes:
      - ReadWriteOnce
    size: 8Gi
  persistentVolumeClaimRetentionPolicy:
    enabled: false
    whenScaled: Retain
    whenDeleted: Retain
sentinel:
  enabled: true
  masterSet: mymaster
  quorum: 2
  getMasterTimeout: 90
  automateClusterRecovery: false
  redisShutdownWaitFailover: true
  downAfterMilliseconds: 60000
  failoverTimeout: 180000
  containerPorts:
    sentinel: 26379
  persistence:
    enabled: true
    path: /data
    storageClass: nfs-share
    accessModes:
      - ReadWriteOnce
    size: 8Gi
  persistentVolumeClaimRetentionPolicy:
    enabled: false
    whenScaled: Retain
    whenDeleted: Retain