- name: k8s-cp
  hosts: k8s_cp
  gather_facts: no
  user: user
  become: yes
  max_fail_percentage: 0
  vars_files:
    - ./env.yml
    - ./vars.yml
  tasks:
    - include_tasks: "./tasks/{{ item }}"
      with_items: "{{ var.k8s_cp.tasks }}"
      when: var.k8s_cp.tasks

- name: k8s-cp-join
  hosts: k8s_cp_join
  gather_facts: no
  user: user
  become: yes
  max_fail_percentage: 0
  vars_files:
    - ./env.yml
    - ./vars.yml
  tasks:
    - include_tasks: "./tasks/{{ item }}"
      with_items: "{{ var.k8s_cp_join.tasks }}"
      when: var.k8s_cp_join.tasks

- name: k8s-wk
  hosts: k8s_wk
  gather_facts: no
  user: user
  become: yes
  max_fail_percentage: 0
  vars_files:
    - ./env.yml
    - ./vars.yml
  tasks:
    - include_tasks: "./tasks/{{ item }}"
      with_items: "{{ var.k8s_wk.tasks }}"
      when: var.k8s_wk.tasks
