- name: apt
  apt:
    name:
    - haproxy
    - keepalived

- name: copy
  copy:
    src: ./files/redundant/cp/haproxy.cfg
    dest: /etc/haproxy/
    mode: '0644'
  ignore_errors: yes

- name: shell
  shell: echo "net.ipv4.ip_nonlocal_bind = 1" >> /etc/sysctl.conf

- name: shell
  shell: sysctl -p

- name: copy
  copy:
    src: ./files/redundant/cp/keepalived.conf
    dest: /etc/keepalived/
    mode: '0644'
  ignore_errors: yes

- name: systemd
  systemd:
    name: keepalived
    state: restarted
    enabled: true
  ignore_errors: yes

- name: systemd
  systemd:
    name: haproxy
    state: restarted
    enabled: true
  ignore_errors: yes