- name: shell
  shell: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

- name: shell
  shell: helm repo add cilium https://helm.cilium.io/

- name: Execute helm
  shell: |
    helm install cilium cilium/cilium \
        --version 1.15.0-pre.2 \
        --namespace kube-system \
        --set kubeProxyReplacement=strict \
        --set k8sServiceHost={{ KUBE_API_SERVER_VIP }} \
        --set k8sServicePort=8443
  register: result
  changed_when: false
- name: Show stdout helm
  debug:
    msg: "{{ result.stdout_lines }}"

- name: shell
  shell: helm repo add argo https://argoproj.github.io/argo-helm

- name: Execute helm
  shell: |
    helm install argocd argo/argo-cd \
        --version 5.51.4 \
        --create-namespace \
        --namespace argocd \
        --values https://raw.githubusercontent.com/megutamago/my-app-k8s/{{ TARGET_BRANCH }}/k8s-manifests/argocd-helm-chart-values.yaml
  register: result
  changed_when: false
- name: Show stdout helm
  debug:
    msg: "{{ result.stdout_lines }}"

- name: Execute helm
  shell: |
    helm install argocd argo/argocd-apps \
        --version 1.4.1 \
        --values https://raw.githubusercontent.com/megutamago/my-app-k8s/{{ TARGET_BRANCH }}/k8s-manifests/argocd-apps-helm-chart-values.yaml
  register: result
  changed_when: false
- name: Show stdout helm
  debug:
    msg: "{{ result.stdout_lines }}"
