# docker secret
- name: copy
  copy:
    src: ./files/secrets/dockerhub-secret.yaml
    dest: /root
    mode: '0644'
  ignore_errors: yes

- name: shell
  shell: kubectl apply -f /root/dockerhub-secret.yaml

- name: file
  file:
    path: /root/dockerhub-secret.yaml
    state: absent

# create namespace n8n
- name: shell
  shell: kubectl create namespace n8n

# create namespace postgres-operator
- name: shell
  shell: kubectl create namespace postgres-operator

# install postgres operator
# https://github.com/zalando/postgres-operator/tree/v1.10.1
- name: shell
  shell: helm repo add postgres-operator-charts https://opensource.zalando.com/postgres-operator/charts/postgres-operator

- name: shell
  shell: helm install postgres-operator postgres-operator-charts/postgres-operator --namespace=postgres-operator

- name: shell
  shell: helm repo add postgres-operator-ui-charts https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui

- name: shell
  shell: helm install postgres-operator-ui postgres-operator-ui-charts/postgres-operator-ui --namespace=postgres-operator

# postgres operator ui LB
# - name: copy
#   copy:
#     src: ./files/cp/postgres-operator-ui-lb.yaml
#     dest: /root
#     mode: '0644'
#   ignore_errors: yes

# - name: shell
#   shell: kubectl apply -f /root/postgres-operator-ui-lb.yaml

# - name: file
#   file:
#     path: /root/postgres-operator-ui-lb.yaml
#     state: absent