- name: k8s-cp
  hosts: k8s_cp
  gather_facts: no
  user: user
  become: yes
  max_fail_percentage: 0
  vars_files:
    - ./env.yml
  tasks:
    - import_tasks : ./tasks/common/common.yml
    - import_tasks : ./tasks/other/nfs-client.yml
    - import_tasks : ./tasks/k8s-cp/ha-master.yml
    - import_tasks : ./tasks/common/k8s.yml
    - import_tasks : ./tasks/k8s-cp/setup.yml
    - import_tasks : ./tasks/other/parameter.yml

- name: k8s-cp-join
  hosts: k8s_cp_join
  gather_facts: no
  user: user
  become: yes
  max_fail_percentage: 0
  vars_files:
    - ./env.yml
  tasks:
    #- import_tasks : ./tasks/common/common.yml
    #- import_tasks : ./tasks/other/nfs-client.yml
    #- import_tasks : ./tasks/common/k8s.yml
    #- import_tasks : ./tasks/k8s-cp/join.yml
    #- import_tasks : ./tasks/other/parameter.yml

- name: k8s-wk
  hosts: k8s_wk
  gather_facts: no
  user: user
  become: yes
  max_fail_percentage: 0
  vars_files:
    - ./env.yml
  tasks:
    - import_tasks : ./tasks/common/common.yml
    - import_tasks : ./tasks/other/nfs-client.yml
    - import_tasks : ./tasks/common/k8s.yml
    - import_tasks : ./tasks/k8s-wk/setup.yml
    - import_tasks : ./tasks/other/parameter.yml