- name: k8s-cp
  hosts: k8s_cp
  gather_facts: no
  user: user
  become: yes
  max_fail_percentage: 0
  vars_files:
    - ./env.yml
  tasks:
    - import_tasks : ./tasks/common.yml
    - import_tasks : ./tasks/nfs-client.yml
    - import_tasks : ./tasks/ha-master.yml
    - import_tasks : ./tasks/common.yml
    - import_tasks : ./tasks/setup.yml
    - import_tasks : ./tasks/parameter.yml

- name: k8s-cp-join
  hosts: k8s_cp_join
  gather_facts: no
  user: user
  become: yes
  max_fail_percentage: 0
  vars_files:
    - ./env.yml
  tasks:
    #- import_tasks : ./tasks/common.yml
    #- import_tasks : ./tasks/nfs-client.yml
    #- import_tasks : ./tasks/k8s-cp-join.yml
    #- import_tasks : ./tasks/parameter.yml

- name: k8s-wk
  hosts: k8s_wk
  gather_facts: no
  user: user
  become: yes
  max_fail_percentage: 0
  vars_files:
    - ./env.yml
  tasks:
    - import_tasks : ./tasks/common.yml
    - import_tasks : ./tasks/nfs-client.yml
    - import_tasks : ./tasks/k8s-wk.yml
    - import_tasks : ./tasks/parameter.yml